//
// MonsterView.h
// Generated by Core Animator version 1.0.3 on 3/18/15.
//
// DO NOT MODIFY THIS FILE. IT IS AUTO-GENERATED AND WILL BE OVERWRITTEN
//

#import <UIKit/UIKit.h>

IB_DESIGNABLE
@interface MonsterView : UIView

@property (strong, nonatomic) NSDictionary *viewsByName;

// t1
- (void)addT1Animation;
- (void)addT1AnimationWithCompletion:(void (^)(BOOL finished))completionBlock;
- (void)addT1AnimationAndRemoveOnCompletion:(BOOL)removedOnCompletion;
- (void)addT1AnimationAndRemoveOnCompletion:(BOOL)removedOnCompletion completion:(void (^)(BOOL finished))completionBlock;
- (void)addT1AnimationWithBeginTime:(CFTimeInterval)beginTime andFillMode:(NSString *)fillMode andRemoveOnCompletion:(BOOL)removedOnCompletion completion:(void (^)(BOOL finished))completionBlock;
- (void)removeT1Animation;

- (void)removeAllAnimations;

@end