//
// CrazymanView.h
// Generated by Core Animator version 1.0.3 on 3/20/15.
//
// DO NOT MODIFY THIS FILE. IT IS AUTO-GENERATED AND WILL BE OVERWRITTEN
//

#import <UIKit/UIKit.h>

IB_DESIGNABLE
@interface CrazymanView : UIView

@property (strong, nonatomic) NSDictionary *viewsByName;

// Untitled Animation
- (void)addUntitledAnimation;
- (void)addUntitledAnimationWithCompletion:(void (^)(BOOL finished))completionBlock;
- (void)addUntitledAnimationAndRemoveOnCompletion:(BOOL)removedOnCompletion;
- (void)addUntitledAnimationAndRemoveOnCompletion:(BOOL)removedOnCompletion completion:(void (^)(BOOL finished))completionBlock;
- (void)addUntitledAnimationWithBeginTime:(CFTimeInterval)beginTime andFillMode:(NSString *)fillMode andRemoveOnCompletion:(BOOL)removedOnCompletion completion:(void (^)(BOOL finished))completionBlock;
- (void)removeUntitledAnimation;

- (void)removeAllAnimations;

@end